name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  update-stats:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run
      run: make
